import{createRequire}from'node:module';import{writeFile}from'node:fs/promises';import{execFileSync}from'node:child_process';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),contexts=[],passed=[],errors=[],base='http://127.0.0.1:8091';
const check=(v,n)=>{if(!v)throw Error(n);passed.push(n);console.log('PASS '+n);};
const marker='Final acceptance '+Date.now();
async function ctx(width){const c=await browser.newContext({viewport:{width,height:900}});contexts.push(c);await c.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));return{c,p};}
async function submit(p,selector,click){const response=p.waitForResponse(r=>r.url().endsWith(selector)&&r.request().method()==='POST');await click();const r=await response;check(r.status()===200,'real HTTP '+selector+' accepted');return r.json();}
try{
 let primary;
 for(const width of[390,1366]){
  const g=await ctx(width),p=g.p;if(width===390)primary=g;
  await p.goto(base+'/',{waitUntil:'domcontentloaded'});check(await p.evaluate(()=>typeof window.VPNChatOpen==='function'&&!!document.getElementById('vpn-chat-panel')),'real page preloads widget before first click '+width);check(await p.evaluate(()=>{document.getElementById('vpn-chat-launch').click();return !document.getElementById('vpn-chat-panel').hidden;}),'real panel opens in same click handler '+width);await p.locator('#vpn-chat-welcome').waitFor({state:'visible'});await p.waitForFunction(()=>!document.getElementById('vpn-chat-start-button').disabled);
  check(!await p.locator('#vpn-chat-contact').isVisible(),'real prechat has no email form '+width);
  await p.locator('#vpn-chat-first').fill(marker+' '+width);await submit(p,'/guest/start',()=>p.locator('#vpn-chat-start-button').click());await p.locator('#vpn-chat-reply').waitFor({state:'visible'});
  await p.locator('#vpn-chat-log .vpn-chat-message').filter({hasText:marker}).waitFor();check(true,'button send persists message '+width);
  await p.waitForFunction(()=>!document.getElementById('vpn-chat-send-button').disabled);await p.locator('#vpn-chat-message').fill('Enter reply '+width);await submit(p,'/guest/send',()=>p.locator('#vpn-chat-message').press('Enter'));await p.waitForFunction(()=>document.querySelectorAll('#vpn-chat-log .vpn-chat-message').length===2);
  check(true,'Enter sends one reply '+width);
  let sends=0;const listener=r=>{if(r.url().endsWith('/guest/send'))sends++;};p.on('request',listener);
  await p.locator('#vpn-chat-message').fill('Line one');await p.locator('#vpn-chat-message').press('Shift+Enter');await p.waitForTimeout(150);check(sends===0&&(await p.locator('#vpn-chat-message').inputValue()).includes('\n'),'Shift+Enter creates newline without sending '+width);
  await p.locator('#vpn-chat-message').dispatchEvent('keydown',{key:'Enter',isComposing:true});await p.waitForTimeout(150);check(sends===0,'IME Enter does not send prematurely '+width);p.off('request',listener);
  await p.locator('#vpn-chat-message').fill('');await p.locator('#vpn-chat-contact-email').fill('buyer-'+width+'@example.invalid');await submit(p,'/guest/contact',()=>p.locator('#vpn-chat-contact-save').click());await p.locator('#vpn-chat-contact').waitFor({state:'hidden'});check(await p.locator('#vpn-chat-add-email').innerText()==='Edit email','real email save updates UI '+width);
  await p.reload();await p.locator('#vpn-chat-launch').click();await p.locator('#vpn-chat-log .vpn-chat-message').first().waitFor();check(await p.locator('#vpn-chat-log .vpn-chat-message').count()===2,'reload restores actual saved history without duplicates '+width);
  await p.locator('#vpn-chat-add-email').click();check(await p.locator('#vpn-chat-contact-email').inputValue()==='buyer-'+width+'@example.invalid','real saved email restored '+width);
  await p.locator('#vpn-chat-contact-dismiss').click();await p.locator('#vpn-chat-panel').screenshot({path:`artifacts/vpn-live-chat/evidence/final-real-chat-${width}.png`});
  const box=await p.locator('#vpn-chat-message').boundingBox();check(box.x>=0&&box.x+box.width<=width&&box.y+box.height<=900,'real composer fits viewport '+width);
 }
 const staff=await ctx(1366),sales=staff.p;await sales.goto(base+'/wp-login.php');await sales.locator('#user_login').fill('agent-a');await sales.locator('#user_pass').fill('test-password-local-only');await Promise.all([sales.waitForURL('**/wp-admin/**'),sales.locator('#wp-submit').click()]);await sales.goto(base+'/wp-admin/admin.php?page=vpn-live-chat');
 const row=sales.locator('.vpn-row').filter({hasText:'buyer-390@example.invalid'});await row.waitFor({timeout:20000});await row.click();await sales.locator('#vpn-reply').waitFor({state:'visible'});await sales.locator('#vpn-message').fill('Final isolated sales reply');await primary.p.locator('#vpn-chat-close').click();await submit(sales,'/agent/send',()=>sales.locator('#vpn-agent-send').click());check(true,'sales inbox claims and replies through real HTTP');
 await primary.p.evaluate(()=>window.dispatchEvent(new Event('focus')));await primary.p.waitForFunction(()=>!document.getElementById('vpn-chat-unread').hidden,null,{timeout:20000});check(true,'minimized widget shows genuine sales unread');await primary.p.locator('#vpn-chat-launch').click();await primary.p.locator('#vpn-chat-log .vpn-chat-message').filter({hasText:'Final isolated sales reply'}).waitFor();check(true,'guest receives sales response');await primary.p.waitForFunction(()=>document.getElementById('vpn-chat-unread').hidden);check(true,'visible response read acknowledgement clears badge');check(errors.length===0,'real pages have no JavaScript errors');
}finally{await browser.close();await writeFile('artifacts/vpn-live-chat/evidence/final-real-browser-report.json',JSON.stringify({version:'1.8.1',checks:passed.length,passed,mode:'real WordPress HTTP + InnoDB on isolated 8091/3311; external HTTP/mail blocked; no CAPTCHA mocks needed',errors},null,2));execFileSync('C:/xampp/php/php.exe',['tests/live-chat/final-acceptance.php'],{stdio:'ignore'});}
