import {createRequire} from 'node:module';import {readFile,writeFile}from'node:fs/promises';import{execFileSync}from'node:child_process';
const require=createRequire(import.meta.url);const{chromium}=require('C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),base='http://localhost/hopgiayvpn',marker='Identity QA '+Date.now(),email='identity-'+Date.now()+'@example.invalid',passed=[],created=[],contexts=[];
const check=(v,n)=>{if(!v)throw Error(n);passed.push(n);console.log('PASS '+n);};
async function ctx(){const c=await browser.newContext({viewport:{width:1366,height:900}});contexts.push(c);await c.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());return c;}
async function api(c,path,data,csrf){const r=await c.request[ data===undefined?'get':'post'](base+'/wp-json/vpn-chat/v1/'+path,{headers:{Origin:'http://localhost','X-VPN-CSRF':csrf||''},...(data===undefined?{}:{data})});return{status:r.status(),...(await r.json())};}
const boot=c=>api(c,'bootstrap',{});
const code=async id=>(JSON.parse(await readFile('tests/live-chat/runtime/verification-mailbox.json','utf8')))[id].code;
async function start(c,b,text){const t=await c.request.get(base+'/wp-json/vpn-chat-local/v1/challenge');const q=await t.json();const r=await api(c,'guest/start',{message:text,client_message_id:crypto.randomUUID().replaceAll('-',''),challenge:q.token},b.csrf);if(r.status!==200)throw Error(JSON.stringify(r));created.push(r.id);return r;}
const db=(action,id)=>execFileSync('C:/xampp/php/php.exe',['tests/live-chat/identity-fixture.php',action,id],{encoding:'utf8'});
try{
const a=await ctx(),b=await ctx();let ab=await boot(a),bb=await boot(b);check(ab.status===200&&ab.customer.code!==bb.customer.code,'separate anonymous customer codes');let first=await start(a,ab,marker+' first');
let r=await api(b,'guest/sync?id='+first.id,undefined,bb.csrf);check(r.status===404,'another anonymous customer cannot read history');
const visitor=(await a.cookies()).find(x=>x.name==='vpn_chat_visitor');check(visitor.httpOnly&&visitor.sameSite==='Strict'&&visitor.expires>Date.now()/1000+179*86400,'180-day HttpOnly persistent visitor cookie');
await a.clearCookies({name:'vpn_chat_session'});ab=await boot(a);check(ab.conversation===first.id,'short session replacement restores same conversation');
const c=await ctx();let cb=await boot(c);await c.addCookies([visitor]);cb=await boot(c);check(cb.customer.code!==ab.customer.code,'valid current session does not silently switch identity from another cookie');
const clone=await ctx();await clone.addCookies([visitor]);const cloneBoot=await boot(clone);check(cloneBoot.conversation===first.id,'persistent visitor restores authorized history');
const req=await api(a,'guest/identity/request',{email},ab.csrf);check(req.status===200&&!('code'in req),'request never returns verification code');
r=await api(b,'guest/identity/verify',{request_id:req.request_id,code:await code(req.request_id)},bb.csrf);check(r.status===400,'code is bound to requesting session');
r=await api(a,'guest/identity/verify',{request_id:req.request_id,code:'000000'},ab.csrf);check(r.code==='invalid_verification_code','wrong code rejected');
r=await api(a,'guest/identity/verify',{request_id:req.request_id,code:await code(req.request_id)},ab.csrf);check(r.verified,'first browser email verification succeeds');ab=await boot(a);check(ab.customer.verified_email===email&&ab.conversation===first.id,'verified profile retains anonymous conversation');
const cloneAfter=await boot(clone);check(cloneAfter.conversation===null,'unverified source browser grants revoked after identity merge');
r=await api(a,'guest/identity/verify',{request_id:req.request_id,code:await code(req.request_id)},ab.csrf);check(r.code==='verification_expired','code cannot be reused');
// A different browser still cannot read merely by storing the same contact email.
let second=await start(b,bb,marker+' second');r=await api(b,'guest/contact',{id:second.id,email},bb.csrf);r=await api(b,'guest/sync?id='+first.id,undefined,bb.csrf);check(r.status===404,'unverified matching contact email does not expose other chat');
const req2=await api(b,'guest/identity/request',{email},bb.csrf);r=await api(b,'guest/identity/verify',{request_id:req2.request_id,code:await code(req2.request_id)},bb.csrf);check(r.verified,'second browser verifies same email');bb=await boot(b);check(bb.customer.code===ab.customer.code&&bb.history.some(x=>x.id===first.id)&&bb.history.some(x=>x.id===second.id),'two browsers share one profile and both conversations');
r=await api(b,'guest/sync?id='+first.id,undefined,bb.csrf);check(r.messages.some(x=>x.body===marker+' first'),'verified other browser can restore history');
const p=await b.newPage();await p.goto(base+'/');await p.locator('#vpn-chat-launch').click();await p.locator('#vpn-chat-history').waitFor({state:'visible'});check(await p.locator('#vpn-chat-history option').count()===2,'widget presents conversation history');await p.locator('#vpn-chat-history').selectOption(first.id);await p.locator('.vpn-chat-message').filter({hasText:marker+' first'}).waitFor();check(true,'widget switches to restored chat');await p.setViewportSize({width:390,height:844});check(await p.locator('#vpn-chat-message').evaluate(e=>{const r=e.getBoundingClientRect();return r.x>=0&&r.right<=390&&r.bottom<=844;}),'restored chat composer fits mobile');await p.locator('#vpn-chat-panel').screenshot({path:'artifacts/vpn-live-chat/evidence/identity-restored-mobile.png'});
// Close both and create a fresh conversation without losing customer identity.
db('close',first.id);db('close',second.id);await p.reload();await p.locator('#vpn-chat-launch').click();await p.locator('#vpn-chat-new').waitFor({state:'visible'});await p.locator('#vpn-chat-new').click();await p.waitForFunction(()=>document.getElementById('vpn-chat-state').textContent==='Ready to send.');await p.locator('#vpn-chat-first').fill(marker+' third');const response=p.waitForResponse(r=>r.url().endsWith('/guest/start'));await p.locator('#vpn-chat-start-button').click();const third=await(await response).json();if(third.id)created.push(third.id);check(!!third.id,'new chat works after closed history');bb=await boot(b);check(bb.history.length===3&&bb.customer.code===ab.customer.code,'new conversation stays in same customer profile');
const ui=await ctx(),up=await ui.newPage();await up.goto(base+'/');await up.locator('#vpn-chat-launch').click();await up.locator('#vpn-chat-restore summary').click();await up.locator('#vpn-chat-identity-email').fill(email);const sent=up.waitForResponse(r=>r.url().endsWith('/guest/identity/request'));await up.locator('#vpn-chat-code-request').click();const uiReq=await(await sent).json();if(!uiReq.request_id)throw Error(JSON.stringify(uiReq));await up.locator('#vpn-chat-code').fill(await code(uiReq.request_id));await up.locator('#vpn-chat-code-verify').click();await up.waitForFunction(()=>document.getElementById('vpn-chat-state').textContent==='Email verified. Your conversations are restored.');await up.locator('#vpn-chat-history').waitFor({state:'visible'});check(await up.locator('#vpn-chat-history option').count()===3,'visitor can restore via email UI before sending a chat');await up.setViewportSize({width:390,height:844});await up.locator('#vpn-chat-panel').screenshot({path:'artifacts/vpn-live-chat/evidence/identity-restore-mobile.png'});
db('block',third.id);await b.clearCookies({name:'vpn_chat_session'});const blocked=await boot(b);check(blocked.status===403,'persistent cookie cannot bypass customer block');db('unblock',third.id);bb=await boot(b);check(bb.conversation===third.id,'unblocking restores customer access');
// Attempt limit and expiry are enforced on independent test identity.
const d=await ctx(),dbb=await boot(d),request3=await api(d,'guest/identity/request',{email:'limit-'+Date.now()+'@example.invalid'},dbb.csrf);for(let i=0;i<5;i++)await api(d,'guest/identity/verify',{request_id:request3.request_id,code:'000000'},dbb.csrf);r=await api(d,'guest/identity/verify',{request_id:request3.request_id,code:await code(request3.request_id)},dbb.csrf);check(r.code==='verification_expired','five wrong attempts exhaust code');
const exp=await api(d,'guest/identity/request',{email:'expire-'+Date.now()+'@example.invalid'},dbb.csrf);db('expire-code',exp.request_id);r=await api(d,'guest/identity/verify',{request_id:exp.request_id,code:await code(exp.request_id)},dbb.csrf);check(r.code==='verification_expired','expired code is rejected');
const noCsrf=await api(d,'guest/identity/request',{email});check(noCsrf.status===403,'identity request requires CSRF');const http=await d.request.get(base+'/tests/live-chat/runtime/verification-mailbox.json');check(http.status()===403,'local mailbox is not publicly accessible');
// Actual admin group rendering.
const creds=JSON.parse(await readFile('tests/live-chat/runtime/local-demo-access.json','utf8'));const adm=await ctx(),ap=await adm.newPage();await ap.goto(base+'/wp-login.php');await ap.locator('#user_login').fill(creds.login);await ap.locator('#user_pass').fill(creds.password);await Promise.all([ap.waitForURL(u=>!u.href.includes('wp-login.php')),ap.locator('#wp-submit').click()]);await ap.goto(base+'/wp-admin/admin.php?page=vpn-live-chat');await ap.locator('#vpn-filter').selectOption('all');await ap.locator('#vpn-search').fill(email);await ap.waitForFunction(()=>document.querySelectorAll('#vpn-list .vpn-row').length===1);check(await ap.locator('#vpn-list .vpn-row').count()===1,'admin groups conversations under one customer');await ap.locator('#vpn-list .vpn-row').click();await ap.locator('.vpn-customer-history').waitFor();check(await ap.locator('.vpn-customer-history option').count()===3,'admin can select all authorized histories');await ap.screenshot({path:'artifacts/vpn-live-chat/evidence/identity-admin.png'});
}finally{await writeFile('artifacts/vpn-live-chat/evidence/identity-report.json',JSON.stringify({version:'1.5.0',checks:passed.length,passed,created_fixture_ids:created,marker},null,2));for(const c of contexts)await c.close();await browser.close();}
