import {createRequire}from'node:module';import{readFile,writeFile}from'node:fs/promises';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),passed=[];
const check=(v,n)=>{if(!v)throw Error(n);passed.push(n);console.log('PASS '+n);};
const base='http://localhost',asset='/wp-content/plugins/vpn-live-chat/assets/',files=new Map();for(const name of['launcher.js','launcher.css','widget.js','chat.css','tho-nguyen.png'])files.set(name,await readFile('wp-content/plugins/vpn-live-chat/assets/'+name));
async function fixture(viewport,reducedMotion='no-preference',enabled=true){const c=await browser.newContext({viewport,reducedMotion}),p=await c.newPage();let boot=0,start=0;await c.route('**/*',async r=>{const u=new URL(r.request().url());if(u.pathname.startsWith(asset)){const name=u.pathname.slice(asset.length);return r.fulfill({contentType:name.endsWith('.css')?'text/css':name.endsWith('.png')?'image/png':'text/javascript',body:files.get(name)});}if(u.pathname.startsWith('/wp-json/vpn-chat/v1/')){if(u.pathname.endsWith('/bootstrap')){boot++;return r.fulfill({json:{csrf:'fixture',conversation:null,config:{accepting:true,online:true,presence:'online',agent_available:true,support:{name:'Tho Nguyen',avatar:base+asset+'tho-nguyen.png'},max_chars:2000,site_key:''},customer:{code:'TEST'},history:[]}});}if(u.pathname.endsWith('/guest/start'))start++;return r.fulfill({json:{}});}const cfg={api:base+'/wp-json/vpn-chat/v1/',bundle:base+asset+'widget.js',css:base+asset+'chat.css',bottom:100,support:{name:'Tho Nguyen',avatar:base+asset+'tho-nguyen.png'},greeting_enabled:enabled};return r.fulfill({contentType:'text/html',body:`<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="${asset}launcher.css"><style>body{margin:0;background:#f6fafc;font:16px Arial;color:#17313b}header{padding:24px;background:white;border-bottom:1px solid #dce8ee}main{max-width:960px;padding:40px}h1{font-size:40px}.mobile-conversion-bar{position:fixed;bottom:0;right:0;height:62px;width:100%;background:#fff;border-top:1px solid #ddd}</style><header>VPN PACKAGING FACTORY</header><main><h1>Custom packaging, made for your brand.</h1><p>Explore our paper boxes and packaging solutions.</p></main><div class="mobile-conversion-bar">Request a quote</div><script>window.VPNChatLauncher=${JSON.stringify(cfg)}</script><script src="${asset}launcher.js"></script></html>`});});return {c,p,counts:()=>({boot,start})};}
try{
for(const width of[1366,390]){const f=await fixture({width,height:width===390?844:900});const errors=[];f.p.on('pageerror',e=>errors.push(e.message));await f.p.goto(base+'/invite-test');check(!await f.p.locator('#vpn-chat-greeting').isVisible(),'invitation waits before arrival '+width);await f.p.locator('#vpn-chat-greeting').waitFor({state:'visible'});check((await f.p.locator('#vpn-chat-greeting').innerText()).includes('Need a quote or help choosing packaging?'),'clear invitation copy '+width);check(await f.p.locator('.vpn-chat-invite-avatar img').evaluate(e=>e.complete&&e.naturalWidth>0),'real avatar loads '+width);check(await f.p.locator('.vpn-chat-launch-label').innerText()==='Chat with Sales','label visible on launcher '+width);check(f.counts().boot===0&&f.counts().start===0,'invitation opens no guest session or fake message '+width);check(await f.p.locator('#vpn-chat-launch').evaluate(e=>getComputedStyle(e,'::before').animationIterationCount==='3'),'pulse limited to three cycles '+width);const box=await f.p.locator('#vpn-chat-greeting').boundingBox();check(box.x>=0&&box.y>=0&&box.x+box.width<=width&&box.y+box.height<= (width===390?844:900)-62,'invitation fits and avoids bottom CTA '+width);await f.p.screenshot({path:`artifacts/vpn-live-chat/evidence/invitation-v160-${width}.png`});await f.p.goto(base+'/second-page');await f.p.locator('#vpn-chat-greeting').waitFor({state:'visible'});check(true,'unopened invitation remains available after navigation '+width);await f.p.locator('.vpn-chat-greeting-dismiss').click();await f.p.reload();await f.p.waitForTimeout(2800);check(!await f.p.locator('#vpn-chat-greeting').isVisible(),'explicit dismissal persists '+width);await f.c.close();check(errors.length===0,'no page errors '+width);}
const reduced=await fixture({width:390,height:844},'reduce');await reduced.p.goto(base+'/reduced');await reduced.p.locator('#vpn-chat-greeting').waitFor({state:'visible'});check(await reduced.p.locator('#vpn-chat-launch').evaluate(e=>getComputedStyle(e,'::before').animationName==='none'),'reduced motion disables halo');check(await reduced.p.locator('#vpn-chat-greeting').evaluate(e=>getComputedStyle(e).animationName==='none'),'reduced motion disables entrance');await reduced.p.locator('#vpn-chat-greeting-open').click();await reduced.p.locator('#vpn-chat-panel').waitFor({state:'visible'});check(reduced.counts().boot===1,'invitation action opens real widget');check(!await reduced.p.locator('.vpn-chat-launch-label').isVisible(),'open chat retains compact close button');await reduced.c.close();
const disabled=await fixture({width:1366,height:900},'no-preference',false);await disabled.p.goto(base+'/disabled');await disabled.p.waitForTimeout(2800);check(!await disabled.p.locator('#vpn-chat-greeting').isVisible(),'admin can disable invitation');await disabled.c.close();
}finally{await writeFile('artifacts/vpn-live-chat/evidence/invitation-v160-report.json',JSON.stringify({version:'1.6.0',checks:passed.length,passed,mode:'actual plugin assets with mock homepage/bootstrap; no database messages'},null,2));await browser.close();}
