import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base='http://127.0.0.1:8091',output=new URL('./results/',import.meta.url).pathname.replace(/^\/(\w:)/,'$1');await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),passed=[],errors=[];
function check(ok,name){if(!ok)throw Error(name);passed.push(name);console.log('PASS '+name);}
async function context(options={}){const c=await browser.newContext(options);await c.route('**/*',r=>{
 const host=new URL(r.request().url()).hostname;
 if(host==='challenges.cloudflare.com')return r.fulfill({contentType:'application/javascript',body:`window.turnstile={render:(el,o)=>{window.testChallenge=o;o.callback('valid-ui-'+crypto.randomUUID());return 1;},reset:()=>window.testChallenge.callback('valid-ui-'+crypto.randomUUID())};`});
 return host==='127.0.0.1'?r.continue():r.abort();
});c.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));return c;}
async function login(page,name){await page.goto(base+'/wp-login.php');await page.locator('#user_login').fill(name);await page.locator('#user_pass').fill('test-password-local-only');await Promise.all([page.waitForURL('**/wp-admin/**'),page.locator('#wp-submit').click()]);await page.goto(base+'/wp-admin/admin.php?page=vpn-live-chat');await page.locator('#vpn-filter').waitFor();}
async function presence(page,value){await Promise.all([page.waitForResponse(r=>r.url().includes('agent/sync')&&JSON.parse(r.request().postData()||'{}').presence===value),page.locator('#vpn-presence').selectOption(value)]);}
async function reply(page,text){await page.locator('#vpn-message').fill(text);await page.locator('#vpn-reply button').click();await page.locator('.vpn-msg').filter({hasText:text}).waitFor();}
try{
 const guestContext=await context({viewport:{width:1366,height:900}}),guest=await guestContext.newPage(),calls=[];guest.on('request',r=>calls.push(decodeURIComponent(r.url())));guest.on('response',async r=>{if(r.url().includes('/vpn-chat/')&&r.status()>=400)console.log('API failure '+r.status()+' '+await r.text());});
 await guest.goto(base);await guest.locator('#vpn-chat-greeting').waitFor();check((await guest.locator('#vpn-chat-greeting').innerText()).includes('Hi! How can we help with your packaging project?'),'default proactive greeting copy');
 const round=await guest.locator('#vpn-chat-launch').boundingBox();check(round.width===58&&round.height===58,'launcher is a 58px circle');
 check(await guest.evaluate(()=>getComputedStyle(document.getElementById('vpn-chat-launch')).backgroundColor===getComputedStyle(document.querySelector('.hero .btn-primary')).backgroundColor),'launcher matches actual theme CTA');
 check(!calls.some(u=>u.includes('/vpn-chat/v1/'))&&!(await guestContext.cookies()).some(c=>c.name==='vpn_chat_session'),'greeting creates no chat session or customer message');
 await guest.locator('#vpn-chat-greeting-open').click();await guest.waitForFunction(()=>document.getElementById('vpn-chat-state')?.textContent==='Ready to send.');
 check(await guest.locator('#vpn-chat-title').innerText()==='Tho Nguyen'&&(await guest.locator('#vpn-chat-header-avatar').innerText())==='TN','default header profile uses Tho Nguyen and TN');
 check(await guest.locator('.vpn-chat-auto-label').innerText()==='Automatic welcome','automatic welcome is separate from staff replies');
 await guest.screenshot({path:path.join(output,'ui-start-desktop.png')});
 const name='UI acceptance '+Date.now();await guest.locator('#vpn-chat-name').fill(name);await guest.locator('#vpn-chat-email').fill('ui-acceptance@example.invalid');await guest.locator('#vpn-chat-first').fill('Hello, I need custom packaging.');await guest.locator('#vpn-chat-first').press('Enter');await guest.locator('#vpn-chat-reply').waitFor({state:'visible'});
 await guest.locator('.vpn-chat-message').first().waitFor();await guest.waitForFunction(()=>!document.getElementById('vpn-chat-send-button').disabled);check(await guest.locator('.vpn-chat-message').count()===1,'Enter starts one protected conversation');
 const textarea=guest.locator('#vpn-chat-message');await textarea.fill('First line');await textarea.press('Shift+Enter');await textarea.press('n');check((await textarea.inputValue()).includes('\n'),'Shift+Enter inserts newline');
 const before=calls.length;await textarea.evaluate(el=>{el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));el.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true}));});await new Promise(r=>setTimeout(r,150));check(!calls.slice(before).some(u=>u.includes('guest/send')),'IME Enter does not accidentally send');await textarea.evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await new Promise(r=>setTimeout(r,10));
 await textarea.fill('Tiếng Việt 😊 https://example.invalid/'+('long-link-'.repeat(70)));await textarea.press('Enter');await guest.locator('.vpn-chat-message').filter({hasText:'Tiếng Việt 😊'}).waitFor().catch(async e=>{console.log('Send diagnostic '+await guest.locator('#vpn-chat-state').innerText()+' · length '+(await textarea.inputValue()).length);throw e;});
 check(await guest.locator('#vpn-chat-content').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'long URL/Vietnamese/emoji do not overflow transcript');
 const salesContext=await context({viewport:{width:1366,height:1000}}),sales=await salesContext.newPage();await login(sales,'agent-a');await presence(sales,'available');await sales.locator('.vpn-row').filter({hasText:name}).click();await sales.locator('#vpn-claim').click();await sales.locator('#vpn-reply').waitFor({state:'visible'});
 await textarea.fill('Draft remains when minimized');await guest.locator('#vpn-chat-close').click();await reply(sales,'Tho’s real reply for your packaging project.');await guest.locator('#vpn-chat-unread').waitFor({state:'visible',timeout:25000});check(await guest.locator('#vpn-chat-unread').innerText()==='1','real staff reply creates unread badge while minimized');
 await new Promise(r=>setTimeout(r,16000));check(await guest.locator('#vpn-chat-unread').innerText()==='1','unread badge survives repeated polling');
 await guest.locator('#vpn-chat-launch').click();await guest.locator('.vpn-chat-message').filter({hasText:'Tho’s real reply'}).waitFor();await guest.locator('#vpn-chat-unread').waitFor({state:'hidden'});check(await textarea.inputValue()==='Draft remains when minimized','minimize preserves in-memory draft');
 check(await guest.locator('.vpn-chat-message[data-sender=agent] .vpn-chat-message-name').first().innerText()==='Tho Nguyen','real reply shows server sender name');
 await guest.screenshot({path:path.join(output,'ui-conversation-desktop.png')});
 for(const [label,width,height]of [['mobile',390,844],['small-mobile',320,568]]){
  const mobile=await context({viewport:{width,height},isMobile:true,hasTouch:true,reducedMotion:'reduce'});await mobile.addCookies(await guestContext.cookies());const p=await mobile.newPage();await p.goto(base);await p.locator('#vpn-chat-launch').click();await p.locator('#vpn-chat-reply').waitFor({state:'visible'});await p.locator('.vpn-chat-message').filter({hasText:'Tho’s real reply'}).waitFor();
  const box=await p.locator('#vpn-chat-panel').boundingBox(),composer=await p.locator('.vpn-chat-composer').boundingBox();check(box.x>=0&&box.y>=0&&box.x+box.width<=width+1&&box.y+box.height<=height+1&&composer.y+composer.height<=height+1,label+' panel and composer stay in viewport');
  check(await p.locator('#vpn-chat-content').evaluate(el=>getComputedStyle(el).overflowY==='auto'),label+' transcript scrolls independently');
  check(await p.locator('#vpn-chat-panel').evaluate(el=>getComputedStyle(el).animationName==='none'),label+' reduced motion respected');
  await p.screenshot({path:path.join(output,`ui-conversation-${label}.png`)});await p.setViewportSize({width,height:Math.min(450,height)});await p.locator('#vpn-chat-message').focus();const kb=await p.locator('.vpn-chat-composer').boundingBox();check(kb.y+kb.height<=Math.min(450,height)+1,label+' composer fits resized viewport');await mobile.close();
 }
 await sales.locator('#vpn-owner').selectOption({label:'agent-b'});await sales.locator('#vpn-save').click();await sales.waitForFunction(()=>document.getElementById('vpn-owner').value!==String(window.VPNChatAdmin.user));
 const secondContext=await context(),second=await secondContext.newPage();await login(second,'agent-b');await second.locator('#vpn-filter').selectOption('mine');await second.locator('.vpn-row').filter({hasText:name}).click();await second.locator('#vpn-reply').waitFor({state:'visible'});await presence(second,'available');await reply(second,'Linh’s reply after the sales transfer.');await guest.locator('.vpn-chat-message').filter({hasText:'Linh’s reply'}).waitFor({timeout:25000});
 const names=await guest.locator('.vpn-chat-message[data-sender=agent] .vpn-chat-message-name').allTextContents();check(names.includes('Tho Nguyen')&&names.includes('Linh Ngo'),'history keeps profiles of both sales accounts');
 await presence(second,'away');await guest.evaluate(()=>window.dispatchEvent(new Event('focus')));await guest.locator('#vpn-chat-presence').filter({hasText:'Away'}).waitFor();check(true,'header Away comes from assigned agent presence');
 await presence(second,'offline');await guest.evaluate(()=>window.dispatchEvent(new Event('focus')));await guest.locator('#vpn-chat-presence').filter({hasText:'Offline'}).waitFor();check(true,'header Offline comes from server');
 await second.locator('#vpn-read').click();await guest.evaluate(()=>window.dispatchEvent(new Event('focus')));await guest.locator('.vpn-chat-delivery').filter({hasText:'Read'}).first().waitFor();check(true,'Read label appears after real sales acknowledgement');
 await guest.locator('#vpn-chat-close').click();await reply(second,'Unread reply retained across page navigation.');await guest.reload();await guest.locator('#vpn-chat-unread').waitFor({state:'visible',timeout:25000});check(await guest.locator('#vpn-chat-greeting').isHidden()&&await guest.locator('#vpn-chat-panel').isHidden(),'navigation restores unread without repeating greeting or auto-opening panel');
 await guest.locator('#vpn-chat-launch').click();await guest.locator('#vpn-chat-unread').waitFor({state:'hidden'});
 await guest.route(url=>url.href.includes('/guest/sync'),async route=>{const response=await route.fetch(),data=await response.json();data.config.support.avatar=base+'/missing-avatar.png';await route.fulfill({response,json:data});});await Promise.all([guest.waitForRequest('**/missing-avatar.png'),guest.evaluate(()=>window.dispatchEvent(new Event('focus')))]);await guest.waitForFunction(()=>document.getElementById('vpn-chat-header-avatar').textContent==='LN'&&!document.querySelector('#vpn-chat-header-avatar img'));check(true,'failed avatar image falls back to initials');
 await presence(sales,'offline');
 await sales.goto(base+'/wp-admin/admin.php?page=vpn-chat-profile&user_id='+await second.evaluate(()=>window.VPNChatAdmin.user));check(await sales.locator('input[name=profile_name]').inputValue()==='Tho Nguyen','sales profile screen ignores another user ID without manager capability');
 await guest.screenshot({path:path.join(output,'ui-multiple-sales.png')});check(errors.length===0,'no uncaught JS errors across guest/sales/mobile');
 await presence(second,'offline');await guestContext.close();await salesContext.close();await secondContext.close();
 await writeFile(path.join(output,'ui-profile-report.json'),JSON.stringify({checks:passed.length,passed},null,2));console.log('TOTAL '+passed.length+' UI/profile checks passed');
}finally{await browser.close();}
