"""Build the October Christmas product payload; source images remain unchanged."""
from pathlib import Path
import json
import re
import shutil

ROOT = Path(__file__).resolve().parent.parent
THEME = ROOT / 'wp-content/themes/custom-box-theme'
MARKER = 'christmas-gift-boxes-20261001'
CONTENT = THEME / 'inc/product-content' / MARKER
BUNDLE = THEME / 'inc/product-sample-deploy-assets/uploads/2026/10'
CONTENT.mkdir(parents=True, exist_ok=True)
BUNDLE.mkdir(parents=True, exist_ok=True)

def product(prefix, title, keyword, description, categories, visible, use, structure, shape, palette, checks, sections, faq):
    return dict(prefix=prefix, slug='custom-'+prefix, title=title, keyword=keyword,
        seo_title=title.replace('Custom ', '')+' | VPN', seo_description=description,
        seo_category='christmas-packaging', categories=['christmas-packaging','gift-paper-boxes']+categories,
        tags=[keyword,'custom Christmas packaging','seasonal gift packaging'],
        feature=visible, industrial_use=use, paper_type='Material grade, thickness and surface to be selected from the packed-item brief and approved physical sample.',
        box_type=structure, shape=shape, liner_type='Custom insert and contact layers to be specified after measuring the actual contents.',
        color=palette, visual_reference=title+'; design reference, not a verified production sample.',
        content_file=prefix+'.html', caption_detail=visible+' Final material and finish require sample approval.',
        visible=visible, use=use, checks=checks, sections=sections, faq=faq)

products = [
product('burgundy-christmas-candle-window-box','Custom Burgundy Christmas Candle Window Box','Christmas candle window box',
 'Custom burgundy Christmas candle window box with ribbon and front display opening. Specify jar fit, window film, insert and artwork for a quote.',
 ['candle-packaging-boxes','folding-carton-boxes'],
 'Burgundy house-like top, gold-colored bow, rectangular front window and botanical holiday artwork.',
 'Candle brands, home-fragrance retailers and seasonal gift buyers planning a single-jar presentation.',
 'Peaked-top window carton concept; closure, film and base construction require confirmation.',
 'Upright rectangular body with a peaked top.', 'Burgundy, cream and gold-colored decoration.',
 ['Largest jar diameter including label seam','Jar height including lid and any dust cover','Filled glass weight and center of gravity','Window position relative to the candle label','Film attachment and clearance from the glass','Base lock and vertical insert support','Ribbon route and bow clearance','Transport carton and glass protection'],
 [
 ('Make the candle visible without losing its identity', '''The burgundy Christmas candle window box puts a single glass jar behind a rectangular front opening. A peaked upper silhouette and gold-colored bow frame the candle rather than competing with a large printed product picture. This is a useful direction for home-fragrance brands whose jar color, wax appearance or label should remain visible on a seasonal shelf. The pictured jar is a styling reference; it does not establish the product supplied with an order. Start with the actual candle, including its lid and label, and decide which information should be readable through the opening. Place the brand name on the upper front area, away from the bow. Keep scent identity on a panel that remains visible when several cartons stand together.'''),
 ('Measure the glass before choosing carton proportions', '''Use the largest outside diameter of the finished jar, not a nominal candle capacity. Include a raised label seam, lid overhang, decorative band and any wrap that increases the diameter. Measure the overall closed height and identify where the jar carries its weight. A tightly fitted wall can scuff the label; an oversized cavity allows the glass to rotate until the label disappears behind the window edge. Set the insert cavity and wall clearance together. Ask for a blank sample with the real candle installed, then inspect the window alignment from normal shelf height. Record the accepted internal dimensions in the sample brief so a change of jar supplier does not silently change the packaging fit.'''),
 ('Treat the display opening as a structural decision', '''A front window removes material from a load-bearing panel. The remaining border, corner radii and distance to fold lines must be considered with board grade and packed weight. The image shows a transparent-looking opening, but cannot confirm whether there is film, an uncovered cutout or a simulated reflection. Specify the intended window construction explicitly. If film is selected, request its material, attachment area and position relative to the jar. Check for wrinkles, loose edges and adhesive visible from the front. If the opening is uncovered, assess dust exposure and access to the contents during retail handling. Neither option by itself proves that the carton protects glass in a delivery network.'''),
 ('Build support below the jar, not just around it', '''A paperboard cradle, collar or platform may help locate the candle, but the support must work with the base closure. A heavy glass jar should not rely on a decorative front border to remain upright. Discuss how its weight transfers through the insert to the bottom panel and how the bottom is locked or bonded. Test the filled carton while lifting it from its body, setting it down and removing the product. Check whether the candle tips into the window, rubs the film or slips beneath a collar. The visualization does not show an insert, so its shape and material are additional design decisions. Keep the protective components visible in the quotation rather than assuming they are included.'''),
 ('Reserve artwork space for scent and care information', '''The concept places small stars, evergreen sprigs and gold-colored ornament around a burgundy panel. These visual cues can support a holiday collection while leaving a practical label area. Distinguish the candle name from seasonal greetings and keep scent variants legible at actual print size. Put the barcode, batch reference and required candle-use information on a suitable solid panel, using the candle brand's approved wording. Avoid printing essential text across the cut edge or fold. If metallic foil is requested, define the foil area separately from the printed botanical art. A gold appearance in the supplied images is not evidence of foil stamping or a particular coating; confirm the finish on the selected paper.'''),
 ('Keep the ribbon separate from the lifting method', '''The bow sits at the peaked top, creating a gift-ready focal point. Its visible position does not establish how it is fixed or whether the ribbon wraps beneath the box. Specify ribbon width, color, route, attachment and the stage at which it is tied. If the bow is purely decorative, recipients should have a clear way to open the carton without pulling against the glass. Assess overhead clearance when the carton sits in a retail tray or transit case. A bow compressed against adjacent boxes can arrive with a different shape from the concept. Do not assume ribbon strength or a safe carry load from the picture. Validate any functional lifting arrangement with the filled sample.'''),
 ('Plan candle fulfillment and outer protection', '''Decide whether the candle carton is handed over in a shop, delivered in a corporate gift set or shipped individually to a customer. Each route changes the protective brief. For parcel delivery, assess an outer corrugated shipper and cushioning with the actual jar and carton; the display box is a presentation component until testing establishes otherwise. Record how many upright units go in each master carton and whether partitions prevent glass-to-glass contact. Check the condition of windows, corners, bows and labels after the handling agreed for the route. Include packing instructions for the fulfillment team, particularly if ribbon tying and insert assembly occur after candle filling. Freight calculations need the final packed dimensions, not just the decorative box size.'''),
 ('Compare the candle window with a closed presentation box', '''Choose this direction when the candle itself should be visible before purchase and a vertical shelf footprint suits the jar. A closed ribbon presentation box may be more useful for a candle plus matches or a multi-item gift set that needs a broader insert. A carry carton addresses handover, but adds handle-load requirements. Make the decision from the actual retail interaction: must the shopper see the jar label, must staff assemble sets quickly, and does the recipient need a protected glass product during delivery? Keep those requirements in the request for quotation. The important distinction is not simply the burgundy color; it is the relationship among window visibility, upright fit, bottom support and the selected distribution route.''')],
 [('Is a candle supplied with the packaging?','No candle or glass jar is included in this packaging brief. Define the actual jar and contents separately.'),('Is the front window covered with film?','The image does not verify film. Specify an open cutout or a film-covered window and approve the attachment in a physical sample.'),('Can the bow carry a filled glass candle?','A safe carry load has not been established. Treat the bow as decorative unless a functional attachment is designed and tested.')]),
product('christmas-house-window-carry-gift-box','Custom Christmas House Window Carry Gift Box','Christmas house window gift box',
 'Custom Christmas house window gift box with carry handle and holiday facade. Plan window alignment, handle load, inserts and print for your gift set.',
 ['folding-carton-boxes','corporate-gift-packaging'],
 'Red house facade, cream roof-like panels, red carry opening and three arched front windows.',
 'Retailers, event organizers and corporate gift assemblers preparing seasonal handover sets.',
 'House-style carry carton concept with arched openings; handle reinforcement and closure to be confirmed.',
 'House-shaped upright carton with a roof-like top and integrated carry opening.', 'Red, cream, green and gold-colored seasonal graphics.',
 ['Combined product weight and movement','Tallest item below the roof folds','Three-window position and product alignment','Panel bridges between arched openings','Handle grip height and reinforcement','Top closure sequence under the handle','Base support for the complete set','Flat or assembled delivery and packing time'],
 [
 ('Use the house facade to organize a gift reveal', '''This Christmas house window carry gift box uses an illustrated red building as its front panel. Three arched openings, a cream roof-like band and evergreen details turn a seasonal carton into a small display scene. The integrated red carry opening adds a handover cue for retail counters and event gifting. The visible packages behind the windows are styling props rather than a confirmed assortment. Decide whether the three openings should reveal three items, a coordinated backing card or one broader gift behind the facade. This decision changes insert layout and artwork alignment. The carton should remain understandable when a customer views it straight on, with the roof and handle visible above adjacent merchandise.'''),
 ('Map the three arches to the actual contents', '''Three display openings create three visual zones, but do not guarantee three compartments. Measure each gift and sketch its position behind the front panel. A shallow item may disappear from view unless raised on a platform; a wide label may be interrupted by the vertical bridges between arches. Check whether packaging colors form a coherent scene without relying on a perfect arrangement by hand. If products can rotate, include retention or backing in the brief. Avoid assuming that a single insert suits every seasonal assortment. A food gift, beauty set and ornament collection may need different cavity shapes even when the same exterior artwork is used. Approve the filled view using real primary packs rather than substituting unmeasured props.'''),
 ('Protect the facade between the display windows', '''The narrow solid areas between the arches and the lower illustrated band carry part of the front panel's load. Discuss window width, corner shape, distance from folds and film attachment with the selected board construction. The visual package does not identify board thickness or verify a transparent film. Decide whether windows are open or covered and describe any clear layer in the specification. Inspect the bridges for buckling when the box is filled and carried. Keep the artwork clear of the cut paths so a small alignment variation does not clip an essential border or word. A decorative facade may look precise on screen while requiring more generous production clearances in a real die-cut carton.'''),
 ('Set handle clearance above the roof closure', '''The red carry opening appears above the cream roof-like panels. Its grip must remain accessible after the top is folded and the contents are packed. Record the intended finger clearance, handle rise, fold sequence and any reinforcement around the opening. A top panel that presses against the handle can make carrying awkward or disturb the roof shape. The handle must support the whole set through a defined load path to the base, rather than only appearing strong in a render. Evaluate a filled sample for tearing, stretching and closure movement during the expected handover. Do not state a kilogram rating until the construction and test method are agreed. The pictured handle is a design cue, not a load certificate.'''),
 ('Keep the seasonal artwork aligned across roof and walls', '''The house effect relies on the relationship between windows, printed window frames, roof trim and snowy lower scenery. Supply artwork on the final dieline so the red wall and cream roof meet at the approved folds. Reserve a solid logo area that remains readable with the products installed. Consider the front facade as a display face, the side as a place for set information, and the back as a place for the approved barcode or campaign message. Those placements should be reviewed at assembled size. Gold-colored lines in the visualization may be printed color rather than foil. If a specialty finish is desired, define its location and inspect registration around the arched openings on a physical proof.'''),
 ('Choose assembly around the event packing workflow', '''Carry cartons may be supplied flat or in a partially assembled condition, depending on the final structure. Neither state is verified by these images. Ask how the roof closes, how the base is secured, where an insert is loaded and whether window film is already attached. For an event order, assemble a trial set and record the sequence needed by the packing team. Check that staff can distinguish the front orientation and close the top without touching delicate contents. Plan space for gifts, cartons, inserts and completed sets at the packing station. If several assortments share one exterior, define a version label or clear picking rule so the wrong set is not placed behind an identical facade.'''),
 ('Separate festive handover from transport protection', '''The handle is intended to support a handover concept, while the windows and raised roof create exposed presentation features. A master carton or outer shipper may still be required for transport to a store or event venue. Review stack height and packing orientation so the handles are not forced against the next layer. Consider whether dividers or interleaves help protect the window surfaces and printed arches from abrasion. Check the filled box after the agreed handling sequence, including whether products shift behind the windows. If recipients take the gift on a longer journey, define that use in the brief. A carton approved for a counter handover should not automatically be described as a parcel-ready shipping package.'''),
 ('Choose the house format when the scene matters', '''This house-style facade works best when the presentation of several gifts through multiple windows is central to the campaign. A tree-window carry box gives one larger display opening and a different visual hierarchy. A closed rigid-style box can hide mixed product shapes until opening, reducing the need for every item to align with a facade. Compare the formats using product count, packed height, total weight and the desired recipient interaction. The house concept may need more careful insert positioning than a closed box, but that work can make the shelf scene more consistent. Keep the three-window arrangement, roof folding, handle grip and assembly sequence as separate approval points so the artwork does not obscure unresolved structural decisions.''')],
 [('Are there three internal compartments?','Three arched windows are visible, but the insert and compartment layout are not verified. Specify the gift arrangement separately.'),('Does this carry carton ship flat?','The images do not establish the supplied state. Confirm flat, partially assembled or assembled delivery with the approved structure.'),('Can food go directly inside?','Do not infer food-contact suitability. Specify sealed primary packs or verify the proposed direct-contact materials for the intended use.')]),
product('christmas-tree-window-handle-gift-box','Custom Christmas Tree Window Handle Gift Box','Christmas tree window handle box',
 'Custom green Christmas tree window handle box for seasonal gifts. Define the tree opening, handle load, gift layout and logo area before sampling.',
 ['folding-carton-boxes','corporate-gift-packaging'],
 'Green upright carton, tree-shaped front opening, green carry handle and gold-colored botanical border.',
 'Seasonal retailers and gift-set buyers seeking a tree-shaped display with an integrated carry opening.',
 'Handled display carton concept with tree-shaped cutout; film, reinforcement and closure to be agreed.',
 'Tapered-looking upright display carton with a tree-shaped front opening.', 'Evergreen, red, cream and gold-colored accents.',
 ['Contents visible through the narrow tree tip','Gift layout behind wider lower branches','Clearance around cutout corners','Film position and attachment width','Handle rise above the folded top','Total set weight and base construction','Front logo safe area below the tree','Side-wall taper and usable internal space'],
 [
 ('A tree-shaped window makes the contents part of the artwork', '''The Christmas tree window handle gift box combines a green printed body with a tree-shaped front display opening. Small gifts are visible through the tree silhouette, while a gold-colored outline and botanical details reinforce the seasonal theme. The green carry opening sits above the body. This format creates a different retail interaction from a solid printed tree: the actual gift arrangement becomes part of the design. Define what should be visible at the narrow tip, the middle branches and the broad base. The image does not establish a compartment system or included gifts. A clear product arrangement and a stable insert are more useful approval targets than reproducing the exact decorative props shown in the visualization.'''),
 ('Design the insert around the tree silhouette', '''The upper opening is narrow and the lower opening is broad. That shape can hide a product label even when the item fits inside the carton. Measure the products, then draw their visible faces behind the tree before finalizing the cavities. Use the broad lower area for the main visual mass and decide whether smaller items should sit higher on a platform. Check removal clearance so the recipient does not have to force a gift through the window; the intended access should be through the approved top or other closure. For a mixed gift set, record which item belongs in each position. An insert that holds the contents securely also helps maintain the tree scene during the handover.'''),
 ('Review cutout corners and remaining panel strength', '''Each branch point creates an edge that needs a practical die-cut shape. The tree outline should be checked against board grade, coating and the amount of material left around the opening. Avoid treating fine points in the render as a production requirement without reviewing the actual cut path. Specify the desired window radius or corner treatment on the dieline. If a clear film is planned, allow an attachment border outside the visible opening and confirm how it is secured. Inspect the film for wrinkles around the branch tips. If the window is open, review access, dust and exposure of primary packs. The visualization cannot prove tear resistance or identify the composition of a transparent-looking area.'''),
 ('Account for the sides and top while measuring usable space', '''The body appears slightly tapered in some views, but the images do not provide a dimensional drawing. Confirm whether the final carton has straight or angled side walls before calculating its capacity. The nominal outside width can be larger than the useful width at the top, and the folding closure occupies space above the products. Measure internal dimensions at the locations that matter for the real gift set. Include insert thickness and any platform used to raise smaller items. A top that closes easily on an empty carton can bind against a tall gift after filling. Request a blank assembled sample and check the full packing and opening sequence rather than approving the outline from a front photograph alone.'''),
 ('Give the handle a defined load path', '''The integrated green handle has a rounded rectangular grip. Specify its clear opening, rise above the carton, reinforcement and relationship to the top closure. The handle needs enough access for the intended recipient without creating an excessive lever on the upper folds. Assess total filled weight, not just the weight of the largest gift, and check how the load reaches the base. In a filled sample, look for stretching at the grip, movement of the closure and distortion around the tree window. The supplied picture is not a safe-load statement. If a gift set becomes heavier during assortment planning, repeat the structural review rather than assuming the original handle remains suitable.'''),
 ('Protect logo legibility beneath the decorative opening', '''A small logo panel appears below the tree window, surrounded by seasonal detailing. Keep that panel large enough for the real brand name and avoid crowding it with a greeting, legal text and barcode at the same time. Place detailed set information on a solid side or back panel. Check gold-colored border contrast on the approved green print, especially if a textured or matte surface is selected. Red accents can be printed on the carton or supplied by the visible gifts; decide which elements need to remain constant when assortments change. If foil or another special finish is requested, mark the area explicitly and review it around the die-cut opening using the final paper and production proof.'''),
 ('Test the retail display after the gifts are loaded', '''Stand several filled cartons together and view them from the intended shelf height. Check whether the tree outlines remain clear, whether the logo is readable, and whether any item falls out of sight behind a branch. A display sample should include the real labels and ribbons on the gifts, since they can change the visual balance and cavity fit. For a campaign with several color variants, check that the green exterior does not make dark primary packs disappear behind the opening. Record a packing reference image for staff. Inspect again after the agreed carry and transport handling so the approved display is not limited to a carefully arranged first sample.'''),
 ('Compare one large tree opening with three house windows', '''Choose the tree-window format when one coherent display composition is more important than three separate visual zones. The house carry carton can frame individual items through multiple arches; the tree carton needs the assortment to work within a tapered seasonal outline. A solid gift box may suit products that should remain hidden until opening or do not share a coordinated label palette. For a decision, compare actual product shapes, visibility, insert complexity, carry requirements and packing time. The green color alone does not establish a different structural class. Document the cutout, film, top access, handle and base in the sample brief so the seasonal artwork supports an agreed packaging solution rather than substituting for one.''')],
 [('Is the tree opening a printed illustration?','The concept shows a tree-shaped display opening with contents visible behind it. Its final cutout and any film require a confirmed dieline.'),('Can the box hold a heavy gift set?','Capacity depends on the board, base, handle and insert. Confirm the full set weight and approve filled-sample checks before making a load claim.'),('Can the logo sit inside the window?','Reserve solid panel space for a printed logo. If branding is placed on a product visible through the window, test its alignment with the actual insert.')]),
product('green-ribbon-christmas-rigid-gift-box','Custom Green Ribbon Christmas Rigid Gift Box','green Christmas rigid gift box',
 'Custom green Christmas rigid gift box concept with red ribbon and lift-off-looking lid. Specify board, lid fit, inserts and festive print for a quote.',
 ['rigid-boxes','corporate-gift-packaging'],
 'Dark green rectangular presentation box, crossing red ribbon, bow and gold-colored botanical lid motif.',
 'Corporate gift buyers and retail brands planning a closed seasonal presentation for a measured gift set.',
 'Rigid-style rectangular lid-and-base concept; board construction and removable-lid fit require confirmation.',
 'Low rectangular presentation box with a separate-looking lid.', 'Dark green, red and gold-colored botanical details.',
 ['Inside length width and depth of the full set','Finished lid depth and overlap','Base outside dimensions and opening fit','Wrapped corner thickness and seam position','Red ribbon route and attachment','Bow height in the shipping carton','Insert cavity plan and lifting clearance','Botanical motif placement around the ribbon'],
 [
 ('Start with a closed gift reveal and a restrained seasonal palette', '''The green ribbon Christmas rigid gift box presents a dark green rectangular body with a red ribbon crossing the lid and a gold-colored botanical motif near one corner. The concept uses a closed presentation rather than a window display. This direction suits a brief where the recipient should first see the brand and seasonal detail, then discover the products on opening. Corporate gifts and coordinated retail sets can be assessed against this approach, but the pictured exterior does not establish capacity or an included assortment. The word rigid describes the design direction; board layers, wall construction and actual stiffness still require a material specification and physical sample.'''),
 ('Calculate useful internal space from the complete set', '''List every item, including cards, sleeves and accessories, before specifying the internal footprint. A shallow rectangular box may need a platform or several cavities so products remain visible once the lid is removed. Measure the height above the insert as well as below it, and allow room for the recipient to grasp each item. Do not use the outer box proportions as an estimate of internal capacity because the walls, wrap and insert all consume space. If a gift assortment changes, compare the new item against the approved cavity drawing. A replacement bottle with a wider shoulder can change the fit even when its advertised volume remains the same.'''),
 ('Define lid overlap and opening feel as approval criteria', '''The top appears to be a separate cover, but the visualization does not confirm the lid skirt depth or the friction between lid and base. Specify the intended removable-lid construction with inside lid dimensions and outside base dimensions. Decide how much of the base remains exposed and whether a user can grip the lid comfortably with the ribbon installed. Inspect more than one physical sample for binding, excessive looseness and rubbing at the corners. A close fit should be evaluated with the actual wrap and finish rather than only a plain board model. Record the accepted opening behavior and measurement points so production approval describes something repeatable rather than only a subjective premium feel.'''),
 ('Resolve the red ribbon route before finalizing the dieline', '''The ribbon crosses the green lid and is tied in a bow. It may wrap around the whole box, attach to the lid, or be added as a removable decorative component; the picture cannot determine which. Define width, color, texture, attachment and tying instructions. Decide whether the recipient unties the bow before opening or lifts a decorated lid with the bow intact. A ribbon trapped between lid and base changes the clearance and may rub the wrap. A knot adds height to the shipping configuration. Keep the ribbon separate from a carrying function unless its attachment has been designed and tested for that purpose. Approve the assembled package with the exact ribbon planned for the order.'''),
 ('Use the botanical motif without obscuring the brand', '''The gold-colored sprig sits near the lower-right area of the lid, leaving a broad green field. This can support restrained seasonal artwork with a small logo or message, provided the crossing ribbon does not cover it. Mark the ribbon path on the artwork proof and check the assembled front orientation. Decide whether the motif is printed color, foil, embossing or a combination, and name the process in the specification. The smooth or textured appearance in a render does not verify paper texture, lamination or foil. Review an actual surface sample for color, glare and small-detail clarity. Reserve the underside or a solid side panel for labels and set information that do not belong on the presentation face.'''),
 ('Specify the board wrap and visible corner treatment', '''A rigid-style box can be developed with wrapped board, but the selected construction should identify the board grade, cover paper, inner lining and adhesive approach. Check wrap turn-ins, seam placement and corner buildup on a physical sample. The dark green surface can make scuffs or uneven corner folds noticeable, so agree the acceptable appearance for the intended retail presentation. If a textured paper is desired, inspect how the motif prints and how the texture behaves around edges. Do not infer a particular thickness from the pictured wall. The combination of material, span, filled weight and handling determines the structural brief. Include the liner and any insert finish separately so the interior does not remain an unresolved detail behind a polished exterior.'''),
 ('Plan assembled-box storage and outer shipping volume', '''A rigid-style presentation box may occupy its full volume during storage unless a separately designed collapsible structure is specified. The images do not show collapsibility. Ask whether the order will arrive assembled and how bows are protected within master cartons. Include finished lid height, ribbon knot height, carton count and gross packed weight when assessing freight. If gifts ship directly to recipients, evaluate an outer shipper that limits lid movement and prevents abrasion against the green wrap. Review corners, bow shape and insert retention after the handling agreed for the route. A polished presentation surface does not establish parcel resistance. Keep the retail opening experience and the transit arrangement connected in the sample approval.'''),
 ('Select this format for concealment and a simple opening sequence', '''This direction can be assessed when a single lift-off reveal and a compact horizontal arrangement suit the gifts. A tree-window carry carton is more appropriate when visibility before purchase and an integrated grip are central to the brief. A cylindrical gift box changes the insert geometry and round-lid fit. Compare the formats using the actual set, desired shelf position, storage space and recipient interaction. The green box should earn its place through lid fit, organized contents and practical fulfillment, not just the seasonal palette. Keep a record of the accepted lid, ribbon, corner treatment and packed-set photographs for any future order using revised artwork or a different gift assortment.''')],
 [('Is this a magnetic closure box?','A magnetic closure is not visible or verified. The concept shows a separate-looking lid; confirm the opening structure in the drawing and sample.'),('Can it fold flat for shipping?','Collapsibility is not established by these images. A foldable rigid construction must be designed and quoted separately.'),('Is the motif real gold foil?','The motif is gold-colored in the visualization. Confirm printed color, foil or another finish with a physical proof.')]),
product('red-round-christmas-gift-cylinder','Custom Red Round Christmas Gift Cylinder','round Christmas gift box',
 'Custom red round Christmas gift box concept with green ribbon and village print. Define diameter, lid fit, insert, artwork seam and packing for a quote.',
 ['rigid-boxes','paper-tube-packaging'],
 'Red cylindrical body, separate-looking round lid, dark green bow and wrapping holiday village illustration.',
 'Retail gift brands and seasonal set assemblers seeking a round presentation format.',
 'Round gift-cylinder concept with lift-off-looking lid; wound-board or other construction to be confirmed.',
 'Cylindrical presentation box with round lid.', 'Red, cream, dark green and gold-colored village details.',
 ['Usable inside diameter at the smallest point','Inside height with the lid closed','Product corners inside the round footprint','Lid collar depth and removal clearance','Wall build and base attachment','Wrap seam relative to the village illustration','Ribbon bow height and attachment','Carton cells preventing rolling and rubbing'],
 [
 ('A round silhouette changes how the gift is arranged', '''The red round Christmas gift cylinder uses a cylindrical body, a round lid and a dark green bow. A cream and gold-colored village scene wraps around the lower side wall. This format creates a different presentation from a rectangular gift box, especially when the recipient views it from several sides. It can be assessed for a round item or an assortment arranged within a circular footprint, but the supplied images do not show the interior or establish capacity. Start with the contents and the intended opening sequence. Do not assume that a cylinder fits a product simply because its volume appears generous; item corners and the smallest useful inside diameter are the practical constraints.'''),
 ('Measure diameter and product geometry together', '''Measure the inside diameter at the points that matter for the product and insert, allowing for wall layers and any inner lining. A square primary pack needs enough circular space for its corners, not only its face width. For several gifts, sketch their arrangement from above and check that the recipient can remove them without tipping the entire set. Record the usable height with the lid seated and include any platform used to raise short items. A round insert may hold the assortment in place, but its cavity positions must leave enough wall clearance. Approve a blank sample with the actual contents before artwork, especially if the set combines a tall jar and smaller accessories.'''),
 ('Specify the wall build and bottom connection', '''The smooth red cylinder suggests a paper-based presentation direction, but the images do not identify wound board, rolled sheet, wall thickness or the base attachment. Ask for a structural specification suited to the filled weight and handling plan. Inspect the vertical or spiral seam, inside surface and bottom connection in a physical sample. The base should support the contents without relying on the decorative printed sleeve. If an inner platform is used, define how its load transfers to the bottom. A round shape is not evidence of crush resistance or moisture resistance. Material grade, construction and packing need to be agreed as separate requirements, with any performance claim supported by the appropriate filled-package assessment.'''),
 ('Control round-lid fit and collar depth', '''The lid appears separate from the body, with a shallow red rim below the bow. Its actual overlap, collar construction and removal feel are not visible. Specify the seating depth and the inside-lid relationship to the outside cylinder. Check for binding around the full circumference, not just at one point. Review the fit after applying the final paper wrap and finish, since their thickness affects clearance. A loose lid may lift away when a recipient grasps the bow; a tight lid may be difficult to remove without squeezing the body. Agree the intended grip and opening action. Keep the ribbon's decorative role clear unless a functional lifting arrangement has been explicitly developed and tested.'''),
 ('Place the village artwork around a deliberate seam', '''A wrapping illustration needs an agreed beginning, ending and preferred front orientation. Position the wrap seam so it does not interrupt a key house, tree, message or logo. A repeating village pattern may tolerate a joining point better than a single panoramic scene, but the artwork should still be reviewed on the assembled cylinder. Provide the circumferential layout on the approved dieline, including bleed and safe areas at the top and bottom edges. Keep a barcode or essential text on a suitable panel or label area rather than across a curved seam. The gold-colored details in the images do not identify foil or metallic ink; specify the finish separately and inspect its appearance around the actual curved surface.'''),
 ('Plan a round insert that keeps the reveal organized', '''The interior is not shown. For a single jar, an insert may locate the product concentrically and stop it from knocking against the wall. For a mixed set, cavities should keep labels facing the intended opening view and avoid concentrating weight at one edge. Choose the fitment after measuring each primary pack. Include a finger notch or another removal allowance where needed so the user does not have to pull the product by a fragile cap or ribbon. If cushioning is required, define it independently from a decorative lining. A paper cylinder should not be described as direct-food-contact packaging without verifying the proposed materials and use; sealed primary packs and a presentation insert are a different brief.'''),
 ('Keep round boxes from rolling and rubbing in transport', '''A cylindrical gift box needs a packing plan that respects its shape. Consider upright cells, dividers or another arrangement that prevents units rolling against one another during delivery to a retailer. Include the bow height and lid diameter in the master-carton layout. Check whether the red wrap rubs at contact points or whether pressure distorts the lid fit. For direct-to-recipient shipping, assess an outer carton and cushioning with the filled cylinder rather than treating the presentation box as a mailing tube. Record the count per carton, gross weight and orientation for fulfillment. The round silhouette may make the gift distinctive, but it does not remove the need to evaluate handling and storage conditions.'''),
 ('Choose a cylinder for a circular presentation brief', '''This format is a useful direction when the circular reveal and wrapping village artwork serve the gift concept. A rectangular lid-and-base box can fit a grid of products more efficiently, while a window carry carton shows gifts before opening. Compare actual product geometry and insert complexity before choosing a round format. A tall square item may use more of the cylinder's space than expected, and a wide shallow gift may call for a different height-to-diameter relationship. Keep the inside diameter, lid fit, base connection, artwork seam and transport cells as distinct approval points. These details determine whether the seasonal cylinder is practical for the intended order, beyond its red color and decorative bow.''')],
 [('Is this a shipping tube?','The concept is a gift presentation cylinder. Mailing performance and closure retention have not been established; evaluate outer protection for the route.'),('How should the size be specified?','Provide usable internal diameter and closed internal height, plus product dimensions, insert clearance and lid overlap requirements.'),('Are the lid and green ribbon included?','Their appearance is shown, but final components and attachment must be listed in the quotation and approved sample.')])
]

shared = '''<h2>From design reference to a documented production brief</h2>
<p>The supplied images are AI-generated design visualizations, not photographs of a manufactured sample. They show a direction for structure, color and artwork, but cannot verify material grade, dimensions, certification, finish, contents or tested performance. The annotated image uses illustrative labels; it is not a technical drawing. VPN Paper Box Manufacturer works from a project-specific packaging brief. Keep the approved construction, material selection, artwork revision and sample reference together so the written order describes the box you actually need.</p>
<p>Begin with a blank structural sample sized around the real product. Check filling, closing, opening and removal before approving a print layout. Once the structure is agreed, place artwork on that dieline and review a printed sample on the selected material. Fill the sample with the intended contents and assess the handling required for the delivery route. Record acceptance criteria for appearance, fit, component attachment and packaging assembly. The check sequence described here is a proposed buyer workflow, not a claim that these visual concepts have already passed production tests.</p>
<p>If the brief includes recycled content, a certification or a recyclability statement, request documentation for the exact material and final construction. A paper surface alone does not establish the claim. Clear window film, ribbons, coatings, adhesives and inserts may affect separation and disposal instructions. State environmental claims only when the supporting information applies to the components ordered and the intended market. For gifts containing food or cosmetics, specify the primary packaging and contact layers; a decorative outer box does not establish suitability for direct contact with its contents.</p>
<h2>Quotation scope, quantity and seasonal planning</h2>
<p>The standard enquiry MOQ is 1000 boxes; confirm eligible specifications and quantity breaks in the written quotation. The product shown is custom packaging, so a price requires dimensions, construction, material, artwork coverage, finishes and components. Ask the quote to identify whether it includes the insert, ribbon, window film, sample, tooling, assembly and transport packaging. Compare quotations using the same specification and supplied state. A unit price that omits a needed component is not a complete comparison for the finished gift package.</p>
<p>Provide the desired delivery date, destination and any intermediate date when gifts must reach the packing team. Work backward with the supplier to agree structural sampling, artwork approval, printed sampling, production, packing and shipping. No fixed lead time is established by the supplied images. A seasonal campaign benefits from approving the physical reference before production is scheduled, especially when several artwork versions or gift assortments share one structure. Record who approves each revision and keep the final file names associated with the order.</p>
<p>For a useful enquiry, send product dimensions and filled weight, the intended arrangement, order quantity, print files, preferred material or finish, required accessories, packed-delivery format and destination. Mark anything that is still undecided so the quotation can distinguish proposed options from confirmed requirements. If the final package needs an outer shipper, request its dimensions and packing count as part of the logistics discussion. Freight estimates should be based on the complete shipment, including assembled-box volume and protective components.</p>
<p>Browse the {{CATEGORY_LINK}} for other seasonal structures. Compare {{RELATED_ONE_URL}} and {{RELATED_TWO_URL}} against your contents and recipient experience. Use the {{GUIDE_URL}} to organize the sample and artwork approval steps, then {{CONTACT_URL}} with your measured brief. These links help you select an appropriate structure; they do not replace a product-specific drawing, quote or approved physical sample.</p>'''

# v2: match the main keyword to the specific product name; broad collection
# intent remains on the Christmas hub instead of competing across five pages.
keywords = [p['title'].removeprefix('Custom ').lower() for p in products]
descriptions = [
    'Custom burgundy Christmas candle window box with ribbon and front opening. Plan jar fit, window film and logo printing with VPN Packaging in Vietnam.',
    'Custom Christmas house window carry gift box with arched windows. Specify the handle, inserts and logo print for a Vietnam packaging quotation.',
    'Custom Christmas tree window handle gift box with festive green artwork. Plan the window, handle, inserts and logo with VPN Packaging in Vietnam.',
    'Custom green ribbon Christmas rigid gift box concept with red bow. Confirm lid fit, board, inserts and festive printing with VPN Packaging in Vietnam.',
    'Custom red round Christmas gift cylinder with village artwork. Define diameter, lid fit, ribbon and inserts with VPN Packaging in Vietnam.',
]
shared = '''<h2>Custom Christmas packaging from VPN in Vietnam</h2>
<p>VPN Paper Box Manufacturer is a packaging business in Ho Chi Minh City, Vietnam. For a bulk order of custom Christmas gift boxes, send your measured contents, preferred structure and seasonal artwork rather than treating a design image as a finished specification. This page covers one particular format; the {{CATEGORY_LINK}} brings together other gift-box and paper-bag options. The photographs below are existing company images used on VPN's About page. They show the wider production context, not a completed order or a production run of this Christmas design.</p>
{{FACTORY_PROOF}}
<h2>Approve structure, artwork and the filled package</h2>
<p>The product images are AI-generated design visualizations, not manufactured samples. Use them as a design brief. First approve a blank structural sample with the actual contents, then place artwork on the agreed dieline and review a printed sample on the selected material. Check filling, closing, opening and removal. Record accepted dimensions, material, fit, component attachment and artwork revision. For distribution, assess the filled package in its intended outer protection. These are recommended approval steps, not a claim that the pictured concepts have already passed production tests.</p>
<p>If food, cosmetics or fragile glass are included, identify the primary packs and contact layers. A decorative box does not establish direct-contact suitability or transport performance. Request documentation for any proposed certification, recycled-content or environmental statement that applies to the exact ordered materials. Film, ribbon, coatings and inserts should be included in the component specification rather than inferred from the render.</p>
<h2>Request a quote for your custom order</h2>
<p>Standard enquiry MOQ: 1000 boxes; confirm eligible specifications and quantity breaks in the written quotation. Pricing for a bulk or wholesale enquiry depends on size, board, print coverage, finishing, inserts, ribbon, window film and supplied assembly state. Ask what is included, including sample, tooling and transport packaging. Compare quotations using the same finished-package specification rather than a unit price with unresolved accessories.</p>
<p>Send product dimensions and filled weight, item count and layout, order quantity, custom logo and artwork files, preferred materials, finishing, destination and required delivery date. Agree the sample and approval schedule before production. No fixed lead time, stock availability or unit price is established by these images. Keep the final drawing, artwork revision, component list and approved physical reference associated with the written order.</p>
<p>Compare {{RELATED_ONE_URL}} and {{RELATED_TWO_URL}} using your actual contents and desired opening experience. Follow the {{GUIDE_URL}} for seasonal planning, then {{CONTACT_URL}} with your measured brief.</p>'''
for file, target in [('anh-nha-may-1.webp', 'vpn-christmas-factory-worker.webp'),
                     ('anh-nha-may-2.webp', 'vpn-christmas-production-area.webp')]:
    shutil.copy2(THEME/'assets/images'/file, BUNDLE/target)

for i,p in enumerate(products):
    p['keyword'] = keywords[i]
    p['seo_description'] = descriptions[i]
    a,b=products[(i+1)%5],products[(i+3)%5]
    p.update(related_one=a['slug'],related_one_text=a['keyword'],related_two=b['slug'],related_two_text=b['keyword'])
    p['short']=(f"{p['title']} is a seasonal packaging design reference for {p['use'].lower()} "
        f"The concept shows {p['feature'].lower()} Use it to discuss a measured presentation rather than order an unverified size from an image. "
        f"The main planning points are {', '.join(c.lower() for c in p['checks'][:4])}. "
        "Define the actual contents, filled weight and delivery route before selecting paper or board, the insert and any decorative components. "
        "Custom logo placement, seasonal artwork, dimensions and finishing can be scoped around the approved structure. "
        "The supplied images are AI-generated design visualizations, not manufactured samples; contents and performance are not confirmed. "
        "Standard enquiry MOQ: 1000 boxes. Confirm the final material, eligible order quantity, component scope, price and schedule in a written quotation and physical sample.")
    html=f"<p><strong>Quick answer:</strong> {p['title']} is a custom seasonal presentation concept. {p['feature']} It is intended for {p['use'].lower()} The images are AI-generated design visualizations; approve the dimensions, material and filled sample before production.</p>\n"
    for n,(heading,body) in enumerate(p['sections']):
        html+=f'\n<h2>{heading}</h2>\n<p>{body.strip()}</p>\n'
        if n in (1,3,6):html+='\n'+['{{FIGURE_OPEN}}','{{FIGURE_DETAIL}}','{{FIGURE_TOP}}'][(1,3,6).index(n)]+'\n'
    html+='<h2>Product-specific sample acceptance checklist</h2>\n<ul>\n'
    for c in p['checks']:html+=f'<li>{c}: record the agreed requirement and check it on the filled sample.</li>\n'
    html+='</ul>\n'+shared+'\n<h2>Frequently asked questions</h2>\n'
    for q,a in p['faq']:html+=f'<h3>{q}</h3>\n<p>{a}</p>\n'
    (CONTENT/p['content_file']).write_text(html,encoding='utf-8')
    for file in (ROOT/'tmp/christmas-20261001'/p['prefix']).glob('*.webp'):
        target=BUNDLE/file.name
        if target.exists() and target.read_bytes()!=file.read_bytes():raise ValueError('Different existing image: '+file.name)
        shutil.copy2(file,target)

public=[{k:v for k,v in p.items() if k not in ['visible','use','checks','sections','faq']} for p in products]
(CONTENT/'products.json').write_text(json.dumps(public,indent=2),encoding='utf-8')

old=(ROOT/'tools/import-christmas-gift-boxes-20260929.php').read_text(encoding='utf-8')
new=old.replace('20260929','20261001').replace('2026-09-29','2026-10-01').replace('2026/09/','2026/10/')
start=new.index('$products = array(');end=new.index('\nfunction vpn_xmas_gift_',start)
new=new[:start]+"$products = json_decode((string) file_get_contents($content_dir . 'products.json'), true, 512, JSON_THROW_ON_ERROR);\n"+new[end:]
new=new.replace("2 => array('alternate-angle', 'alternate front angle')", "2 => array('front-view', 'front view')").replace("3 => array('printed-detail', 'printed detail')", "3 => array('material-detail', 'surface and window detail')").replace("4 => array('side-profile', 'side profile')", "4 => array('side-view', 'side view')")
new=new.replace('hero|alternate-angle|printed-detail|side-profile|top-view|feature-callouts','hero|front-view|material-detail|side-view|top-view|feature-callouts')
new=new.replace("'post_date' => current_time('mysql'),", "")
# Prepare content and attachments before making each new product publicly visible.
new=new.replace("'post_status' => 'publish',", "'post_status' => $existing ? $existing->post_status : 'draft',")
new=new.replace("wp_update_post(array('ID' => $product_id, 'post_content' => $content));", "if (preg_match('/\\{\\{[A-Z0-9_]+\\}\\}/', $content)) { continue; }\n    $saved = wp_update_post(array('ID' => $product_id, 'post_content' => $content, 'post_status' => 'publish'), true);\n    if (is_wp_error($saved)) { $failures[] = $product['slug'] . ': content save failed'; continue; }")
new=new.replace('Alternate view of the ', 'Front view of the ').replace('alternate view for seasonal', 'front view for seasonal')
new=new.replace("$marker = 'christmas-gift-boxes-20261001';", "require_once get_template_directory() . '/inc/christmas-gift-boxes-20261001-support.php';\n$marker = 'christmas-gift-boxes-20261001';")
new=new.replace("'{{RELATED_ONE_URL}}', '{{RELATED_TWO_URL}}', '{{GUIDE_URL}}', '{{CONTACT_URL}}',", "'{{RELATED_ONE_URL}}', '{{RELATED_TWO_URL}}', '{{GUIDE_URL}}', '{{CONTACT_URL}}', '{{FACTORY_PROOF}}',")
new=new.replace('// Create all product records first', "$factory_proof = vpn_xmas_20261001_factory_proof();\n\n// Create all product records first")
new=new.replace("update_post_meta($product_id, 'rank_math_robots', array('index', 'follow'));", "update_post_meta($product_id, 'rank_math_robots', array('index', 'follow'));\n    update_post_meta($product_id, 'rank_math_canonical_url', get_permalink($product_id));")
new=new.replace("$replacements = array(", "$replacements = array(\n        '{{FACTORY_PROOF}}' => $factory_proof,")
new=new.replace("'post_status' => 'publish'), true)", "'post_status' => ('private' === get_post_status($product_id) ? 'private' : 'publish')), true)")
new=new.replace("    if (function_exists('wc_delete_product_transients'))", "    update_post_meta($product_id, '_vpn_christmas_20261001_source_hash', vpn_xmas_20261001_source_hash($product));\n    update_post_meta($product_id, '_vpn_christmas_20261001_content_hash', hash('sha256', (string) get_post_field('post_content', $product_id)));\n    if (function_exists('wc_delete_product_transients'))")
# Included deploy tools report errors to their caller instead of terminating
# the WP Admin request. The CLI still exits non-zero for an uncaught error.
new=new.replace("fwrite(STDERR, implode(PHP_EOL, array_unique($failures)) . PHP_EOL);\n    exit(1);", "throw new RuntimeException(implode('; ', array_unique($failures)));")
new=new.replace("fwrite(STDERR, implode(PHP_EOL, $asset_errors) . PHP_EOL);\n    exit(1);", "throw new RuntimeException(implode('; ', $asset_errors));")
new=new.replace('    exit(1);', "    throw new RuntimeException('Christmas product import did not complete: ' . implode('; ', $failures));")
start=new.index('function vpn_xmas_gift_20261001_image_files');end=new.index('$category_ids = array();',start)
new=new[:start]+"if (!function_exists('vpn_xmas_gift_20261001_image_files')) {\n"+new[start:end]+"}\n\n"+new[end:]
new = '\n'.join(line.rstrip() for line in new.splitlines()) + '\n'
(ROOT/'tools/import-christmas-gift-boxes-20261001.php').write_text(new,encoding='utf-8')

verify=(ROOT/'tools/verify-christmas-gift-boxes-20260929.php').read_text(encoding='utf-8').replace('20260929','20261001').replace('2026/09/','2026/10/')
start=verify.index('$products = array(');end=verify.index('$required_specs',start)
verify=verify[:start]+"$products = array();\nforeach (json_decode((string) file_get_contents(get_template_directory() . '/inc/product-content/christmas-gift-boxes-20261001/products.json'), true, 512, JSON_THROW_ON_ERROR) as $row) { $products[$row['slug']] = $row; }\n"+verify[end:]
verify=verify.replace("$marker = 'christmas-gift-boxes-20261001';", "require_once get_template_directory() . '/inc/christmas-gift-boxes-20261001-support.php';\n$marker = 'christmas-gift-boxes-20261001';")
verify=verify.replace("if ('publish' !== get_post_status($product_id))", "if (!in_array(get_post_status($product_id), array('publish', 'private'), true))")
verify=verify.replace("    $results[] = array(", "    $failures = array_merge($failures, vpn_xmas_20261001_verify_release($product_id, $expected));\n\n    $results[] = array(")
verify=verify.replace('    exit(1);', "    throw new RuntimeException('Christmas product verification failed: ' . implode('; ', $failures));")
(ROOT/'tools/verify-christmas-gift-boxes-20261001.php').write_text(verify,encoding='utf-8')
for name in ['import-christmas-gift-boxes-20261001.php','verify-christmas-gift-boxes-20261001.php']:
    shutil.copy2(ROOT/'tools'/name,THEME/'inc/product-sample-deploy-tools'/name)

for p in products:
    text=re.sub('<[^>]+>',' ',(CONTENT/p['content_file']).read_text(encoding='utf-8'))
    print(p['slug'],len(text.split()),'long words;',len(p['short'].split()),'short words')
